---
title: "References"
---

Allcott, H., & Rogers, T. (2014). The short-run and long-run effects of behavioral interventions: Experimental evidence from energy conservation. American Economic Review, 104(10), 3003-37

Baumeister, R., Bratslavsky, E., Finkenauer, C., D. Vohs, K.(2001). Bad Is Stronger Than Good. Review Of General Psychology,Vol. 5. No. 4. 323-370

Bicchieri, C. (2006). The Grammar of Society: The Nature and Dynamics of Social Norms. New York: Cambridge University Press.

Bicchieri, C., Dimant, E. (2018). It's Not A Lie If You Believe It: Lying and Belief Distortion Under Norm-Uncertainty, a. University of Pennsylvania, b.Wharton School of Business, c. Behavioral Ethics Lab, d.CeDEx

Cialdini, R. B., Demaine, L. J., Sagarin, B. J., Barrett, D. W., Rhoads, K., & Winter, P. L. (2006). Managing social norms for persuasive impact. Social influence, 1(1), 3-15.

Hallsworth, M., List, J. A., Metcalfe, R. D., & Vlaev, I. (2017). The behavioralist as tax collector: Using natural field experiments to enhance tax compliance. Journal of Public Economics, 148, 14-31.

Levin, I. P., Schneider, S. L., & Gaeth, G. J. (1998). All frames are not created equal: A typology and critical analysis of framing effects. Organizational behavior and human decision processes, 76(2), 149-188.